### ISSUE TITLE
Extension fails to work due to invalid pageURL path

### ISSUE THREAD

**Issue by Redorhcs** [aarontgrogg/Convert-LinkedIn-Profile-to-Printable#4]
Hi Aaron,

In  Convert-LinkedIn-Profile-to-Printable/background.js , the extension fails to work as of 2018-02-24 due to the following segment 

    pageUrl: { hostSuffix: "www.linkedin.com", pathContains: "profile/preview" },

It is searching for profile/preview, whereas now Linkedin has moved to the /in/ format for pages.

Is this repo still maintained? If not, I may be able to look into fixing this sometime in the next month (although my JS isn't that great I'd warn you).

**Comment by aarontgrogg** [comment]
Fixe applied, thanks!
